_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
DATASETS:
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
  PROPOSAL_FILES_TEST: ()
  PROPOSAL_FILES_TRAIN: ()
  TEST: ('keypoints_coco_2017_val',)
  TRAIN: ('keypoints_coco_2017_train',)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "./output/R_50_FPN"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
